# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180211_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='newevent',
            name='template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
