# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180217_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='guests',
            field=models.ManyToManyField(blank=True, to='app.Emails'),
        ),
    ]
