# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180217_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, to='app.Guests'),
        ),
        migrations.DeleteModel(
            name='Emails',
        ),
        migrations.AddField(
            model_name='contact',
            name='guest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Guests'),
            preserve_default=False,
        ),
    ]
