# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180218_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests_limit',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
