# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_event_guests_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guests_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
