# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180218_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_guest', to='app.UserProfile'),
        ),
    ]
